[[pages]]
path = "./account/account.py"
name = "YOUR ACCOUNT"
icon = "💛"

[[pages]]
name = "_________________________________________"
icon = ""
is_section = true

[[pages]]
path = "./home/home.py"
name = "MBTI PERSONA"

[[pages]]
name = "Understand Your Personality!"
icon = "🫵"
is_section = true

[[pages]]
path = "./p_test/p_test.py"
name = "PERSONALITY TEST"
icon = "📝"

[[pages]]
path = "./p_types/p_types.py"
name = "PERSONALITY TYPES"
icon = "💖"

[[pages]]
name = "Contact Us"
icon = "📞"
is_section = true

[[pages]]
path = "./about/about.py"
name = "ABOUT US"
icon = "ℹ️"

