[[pages]]
path = "home.py"
name = "HOME"
icon = "🏠"

[[pages]]
name = "Understand Your Personality!"
icon = "🫵"
is_section = true

[[pages]]
path = "p_test.py"
name = "PERSONALITY TEST"
icon = "📝"

[[pages]]
path = "p_types.py"
name = "PERSONALITY TYPES"
icon = "💖"

[[pages]]
name = "Contact Us"
icon = "📞"
is_section = true

[[pages]]
path = "about.py"
name = "ABOUT"
icon = "ℹ️"

